name: Publish to GitHub Packages

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  publish:
    name: Publish Package
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@tejidosdeagus'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Check npm version
        id: check_npm_version
        run: |
          PKG_VERSION=$(node -p "require('./package.json').version")
          PKG_NAME=$(node -p "require('./package.json').name")
          
          # Try to get the version from npm
          if npm view "$PKG_NAME@$PKG_VERSION" version &> /dev/null; then
            echo "Version $PKG_VERSION already exists in npm"
            echo "should_publish=false" >> $GITHUB_OUTPUT
          else
            echo "Version $PKG_VERSION is new"
            echo "should_publish=true" >> $GITHUB_OUTPUT
          fi
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to GitHub Packages
        if: steps.check_npm_version.outputs.should_publish == 'true'
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }} 